// Pre-fed, clickable suggestions for each Brand Bible context field,
// curated for a streetwear clothing brand. Clicking a chip appends it to the
// field so the founders don't have to think of everything from scratch.
export const BIBLE_OPTIONS = {
  positioning: [
    'Elevated everyday streetwear',
    'Luxury streetwear at an accessible price',
    'Premium basics, done right',
    'Skate-rooted streetwear',
    'Heritage workwear reimagined',
    'Gorpcore / technical outerwear',
    'Y2K-revival graphics brand',
    'Minimalist blank-canvas essentials',
    'Bold graphic statement pieces',
    'Limited-drop hype label',
    'Gender-neutral oversized basics',
    'Sustainable streetwear',
    'Local culture / city-inspired label',
    'Vintage-washed staples',
    'Athleisure-meets-streetwear',
  ],
  audience: [
    'Gen Z (16–24)',
    'Young millennials (25–34)',
    'Students & early-career creatives',
    'Sneakerheads & hype followers',
    'Skaters & street culture',
    'Music & festival crowd',
    'Gym-to-street / athleisure wearers',
    'Thrift & vintage lovers',
    'Design-conscious minimalists',
    'Gender-neutral shoppers',
    'Social-first online buyers',
    'Mid-tier budget ($40–120 a piece)',
    'Premium budget ($120–300 a piece)',
    'Trend-led early adopters',
    'Quality-over-quantity buyers',
  ],
  aesthetic: [
    'Minimal & clean', 'Bold & graphic', 'Vintage / washed', 'Y2K', 'Grunge',
    'Gorpcore / techwear', 'Military / workwear', 'Skate', 'Retro athletic',
    'Monochrome', 'Earth tones', 'Muted / neutral palette', 'High-contrast',
    'Oversized & boxy', 'Distressed / raw edges', 'Japanese streetwear',
    'Brutalist / utilitarian', 'Preppy-street', 'Cyber / futuristic', 'Americana',
    'Heavy-knit & textured', 'Hand-drawn / illustrative graphics', 'Photographic prints',
  ],
  materials: [
    '100% cotton', 'Organic cotton', 'Heavyweight cotton (240–400gsm)',
    'French terry', 'Brushed fleece', 'Loopback jersey', 'Combed ring-spun cotton',
    'Cotton/poly blend', 'Recycled polyester', 'Garment-dyed fabric', 'Pigment-dyed',
    'Acid / mineral wash', 'Ripstop nylon', 'Cordura', 'Twill', 'Canvas / duck cloth',
    'Corduroy', 'Boiled wool', 'Chunky knit / heavy-gauge', 'Bamboo blend',
    'Deadstock / surplus fabric', 'GOTS-certified cotton', 'Suede / faux-suede patches',
    'YKK zippers', 'Custom woven labels', 'Embroidered branding', 'Puff / HD print',
  ],
  fit: [
    'Oversized', 'Boxy', 'Relaxed', 'Regular', 'Slim', 'Cropped', 'Elongated / longline',
    'Drop-shoulder', 'Wide-leg', 'Baggy', 'Tapered', 'Straight-leg', 'Unisex / one-size cut',
    'Heavyweight structured', 'True-to-size', 'Size up for fit', 'Boxy cropped tee',
    'Relaxed hoodie', 'Oversized crewneck', 'Wide cargo pant',
  ],
  quality: [
    'Double-needle stitching', 'Reinforced seams', 'Bar-tacked stress points',
    'Ribbed cuffs & hem', 'Pre-shrunk / garment-washed', 'Side-seamed construction',
    'Tubular knit (budget)', 'Heavyweight 280gsm+ fabric', 'Taped neck seam',
    'Branded YKK hardware', 'Custom woven neck label', 'Tonal embroidery',
    'Colour-fast dyeing', 'Enzyme-washed for softness', 'Locked / clean hems',
    'No loose threads QC', 'Wash-tested for shrinkage', 'Minimum 30 washes durability',
  ],
  sizing: [
    'XS–XXL range', 'S–XL range', 'One-size / free-size', 'Unisex sizing',
    'Inclusive XS–4XL', 'Size chart with body measurements (cm & in)',
    'Garment-measured (flat) chart', 'Fit model: size M', 'Tall-friendly lengths',
    'Consistent grading across styles', 'Runs oversized — size down note',
    'True to size', 'Numbered waist sizing for bottoms', 'Half-size hoodie/tee fit guide',
  ],
  references: [
    'Stüssy', 'Supreme', 'Carhartt WIP', 'Aimé Leon Dore', 'Fear of God / Essentials',
    'Kith', 'Palace', 'Noah', 'Stone Island', 'A-Cold-Wall*', 'Cav Empt', 'Neighborhood',
    'Human Made', 'Corteiz', 'Rhude', 'Awake NY', 'Bode', 'Online Ceramics', 'Brain Dead',
    '90s skate culture', 'Japanese Ura-Harajuku', 'UK garage / grime', 'Hip-hop & rap',
    'Vintage band merch', 'Military surplus', 'Workwear archives', 'Y2K internet aesthetics',
  ],
  avoid: [
    'Fast-fashion logos / knockoffs', 'Overused trend graphics', 'Cheap thin jersey',
    'Plastic / brittle trims', 'Logo-slapping with no concept', 'Gendered marketing clichés',
    'Seasonal over-production', 'Generic stock prints', 'Misaligned / low-res prints',
    'Skin-tight fits', 'Neon fast-fashion palettes', 'AI-generated filler art',
    'Greenwashing claims', 'Copying competitors 1:1', 'Throwaway quality',
  ],
  sustainability: [
    'Small-batch / made-to-order drops', 'Organic & recycled fabrics',
    'Deadstock fabric sourcing', 'Low-waste pattern cutting', 'Plastic-free packaging',
    'Recycled / kraft mailers', 'Water-based / PVC-free inks', 'OEKO-TEX certified dyes',
    'Local / ethical manufacturing', 'Fair-wage factory partners',
    'Carbon-neutral shipping', 'Repair / re-wear program', 'Take-back / recycling scheme',
    'Durable design (anti-throwaway)', 'Transparent supply chain', 'No seasonal overstock burns',
  ],
}
